### ISSUE TITLE
Ability to cycle through list of files contained in arbitraty notes

### ISSUE THREAD

**Issue by ngirard** [chrisgrieser/grappling-hook#1]
### Feature Requested

Hey Chris,

I'm stumbling upon this nice plugin of yours this morning, and it seems like I could very well benefit from it.

The thing is, I'm heavily relying on workspaces, in that I have many workspaces representing as many projects/workflows, and I'm switching between them all day long.
Obsidian only offering a single set of starred files, I have resolved to use dedicated files for "starred contents", simply consisting in itemized wikilinks of relevant files for such and such.

Therefore, it would make much sense to be able to circle through those lists of wikilinks, in both mtime order and "natural" order, the one captured by those files.

(As a side note, I never bothered to mention it to Obsidian's authors, but it would be much beneficial IMHO to rely on markdown files with added semi-structured data as the single way of representing everything, starred files, workspaces, and so on, just like Tiddlywiki and tiddlers. What do you think ?)

Cheers, and thanks for your work !

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
I see the usefulness, but I am not totally sure whether it would make more sense for a plugin like Workspace Plus to implement different sets of starred files though 🤔

**Comment by ngirard** [comment]
I fore sure can see your point. Unfortunately, Workspace Plus has [been staying in a vegetative state](https://github.com/nothingislost/obsidian-workspaces-plus/graphs/contributors) soon after its inception.

**Comment by chrisgrieser** [comment]
sorry for the late response follow up.

Yeah, Workspace Plus not being actively maintained is a bummer. Nonetheless, handling workspaces is out of scope for this plugin, sorry.
