### ISSUE TITLE
Feature Request: Unsure about the meaning of "send text" in the README

### ISSUE THREAD

**Issue by ngirard** [chrisgrieser/grappling-hook#2]
### Feature Requested

I'm unsure whether "send text" means moving or copying the text: it could be worth amending the README to clarify it.

Also, reflecting on my own usage of Obsidian, it seems like I'm doing both moving and copying, the former more frequently than the latter.

Cheers

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
good point, fixed

**Comment by ngirard** [comment]
Great, thanks !
