### ISSUE TITLE
Feature Request: Grappling "between" tabs as opposed to "within" a tab

### ISSUE THREAD

**Issue by nickmilo** [chrisgrieser/grappling-hook#5]
### Feature Requested

Currently, when "Grappling Hook: Switch to Alternate Note" switches to the previous tab, it does so within the current tab, as opposed to navigating to where the previous tab resides.

Can a feature be created to grapple "between" tabs as opposed to "within" a tab

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Good idea. 👍  Added in version 0.8.

Now, if the alternate file is already open in another tab, the command switches to that
tab. If not, the alternate file is opened in the current tab.
